#!/bin/sh

lc=/web/lock/lock

if [ -f $lc ]; then 
echo "Process already running. Please wait and try again later."
exit
    else
{
date > $lc

a1=$(date | awk '{print $6}')
a3=$(date | awk '{print $3}')
mon=$(date | awk '{print $2}')

case $mon in
Jan) a2=01 ;;
Feb) a2=02 ;;
Mar) a2=03 ;;
Apr) a2=04 ;;
May) a2=05 ;;
Jun) a2=06 ;;
Jul) a2=07 ;;
Aug) a2=08 ;;
Sep) a2=09 ;;
Oct) a2=10 ;;
Nov) a2=11 ;;
Dec) a2=12 ;;
esac

case $a3 in
1) a3=01 ;;
2) a3=02 ;;
3) a3=03 ;;
4) a3=04 ;;
5) a3=05 ;;
6) a3=06 ;;
7) a3=07 ;;
8) a3=08 ;;
9) a3=09 ;;
esac

path=$a1-$a2-$a3
cd /web/fortm && rm /web/fortm/*
cd /web/timelapse && rm /web/timelapse/*

full=/home/marka/beward/$path
pp="Beward 1001/1/"
fpath=$full/$pp

#echo "<h3>start!!!</h3>"

cd "$fpath" && ls -t -r |grep jpg |xargs cp --target-directory=/web/fortm

cp /etc/mysc/web/rename /web/fortm/rename

cd /web/fortm && /web/fortm/rename 

ffmpeg -y -r 10 -i %06d.jpg -r 10 -vcodec mjpeg -qscale 1  /web/timelapse/today.avi

cp /web/timelapse/today.avi /home/marka/timelapse/$a1-$mon-$a3.avi

file=/web/timelapse/today.avi

#if [ -f $file ]; then

#echo "<h3> OK timelapse created! http://marka.shcn.ru/timelapse/ </h3>"

#    else echo "Error 24. Email your Administrator"

#fi

rm $lc
}
fi